# Generated by Django 3.1.1 on 2020-12-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_auth', '0002_auto_20201125_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
